### ISSUE TITLE
OTel: Make sure JS uses assembly version in path

### ISSUE THREAD

**Issue by saxx** [adliance/Buddy#16]
It seems that that is not the Assembly-Version of the NuGet package?

<img width="503" alt="image" src="https://github.com/adliance/Buddy/assets/1190606/ffb9fca2-3b29-475e-b043-ca0f7f9ce10f">

**Comment by saxx** [comment]
Maybe we'll need to use "dotnet setversion" in pipeline to set assembly version in nuget package DLL?

**Comment by dmorawetz** [comment]
I added the setversion to the CI pipeline.
